apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |
      [
        {
          "apiVersion": "workspace.che.eclipse.org/v1alpha1",
          "kind": "Workspace",
          "metadata": {
            "name": "petclinic-sample"
          },
          "spec": {
            "started": false,
            "devfile": {
              "apiVersion": "0.0.1",
              "metadata": {
                "name": "petclinic"
              },
              "components": [
                {
                  "id": "org.eclipse.che.editor.theia:next",
                  "name": "theia-ide",
                  "type": "cheEditor"
                },
                {
                  "id": "che-machine-exec-plugin:0.0.1",
                  "name": "exec-plugin",
                  "type": "chePlugin"
                },
                {
                  "name": "mvn-stack",
                  "type": "dockerimage",
                  "image": "maven:3.5.4-jdk-8",
                  "command": [ "/bin/sh", "-c" ],
                  "args": [ "tail -f /dev/null" ],
                  "env": [
                    {
                        "name": "TERM",
                        "value": "xterm"
                    }
                  ],
                  "memoryLimit": "500M",
                  "mountSources": true,
                  "volumes": [
                    {
                      "containerPath": "/root/.m2",
                      "name": "maven-repo"
                    }
                  ],
                  "endpoints": [
                    {
                      "name": "spring-boot",
                      "port": 8080,
                      "attributes": {
                        "discoverable": true,
                        "path": "/api",
                        "protocol": "http",
                        "public": true,
                        "secured": true
                      }
                    }
                  ]
                },
                {
                  "name": "mysql",
                  "type": "kubernetes",
                  "referenceContent": "apiVersion: v1\nkind: List\nitems:\n- apiVersion: v1\n  kind: Pod\n  metadata:\n    name: petclinic\n    labels:\n      app.kubernetes.io/name: petclinic\n      app.kubernetes.io/component: webapp\n      app.kubernetes.io/part-of: petclinic\n  spec:\n    containers:\n    - name: server\n      image: mariolet/petclinic\n      ports:\n      - containerPort: 8080\n        protocol: TCP\n      resources:\n        limits:\n          memory: 512Mi\n- apiVersion: v1\n  kind: Pod\n  metadata:\n    name: petclinic\n    labels:\n      app.kubernetes.io/name: mysql\n      app.kubernetes.io/component: database\n      app.kubernetes.io/part-of: petclinic\n  spec:\n    containers:\n    - name: mysql\n      image: centos/mysql-57-centos7\n      env:\n      - name: MYSQL_USER\n        value: petclinic\n      - name: MYSQL_PASSWORD\n        value: petclinic\n      - name: MYSQL_ROOT_PASSWORD\n        value: petclinic\n      - name: MYSQL_DATABASE\n        value: petclinic\n      ports:\n      - containerPort: 3306\n        protocol: TCP\n      resources:\n        limits:\n          memory: 512Mi\n- kind: Service\n  apiVersion: v1\n  metadata:\n    name: mysql\n    labels:\n      app.kubernetes.io/name: mysql\n      app.kubernetes.io/component: database\n      app.kubernetes.io/part-of: petclinic\n  spec:\n    ports:\n      - name: mysql\n        port: 3306\n        targetPort: 3360\n    selector:\n      app.kubernetes.io/name: mysql\n      app.kubernetes.io/component: database\n      app.kubernetes.io/part-of: petclinic\n- kind: Service\n  apiVersion: v1\n  metadata:\n    name: petclinic\n    labels:\n      app.kubernetes.io/name: petclinic\n      app.kubernetes.io/component: webapp\n      app.kubernetes.io/part-of: petclinic\n  spec:\n    ports:\n      - name: web\n        port: 8080\n        targetPort: 8080\n    selector:\n      app: petclinic\n      component: webapp\n",
                  "selector": {
                    "app.kubernetes.io/component": "database",
                    "app.kubernetes.io/name": "mysql",
                    "app.kubernetes.io/part-of": "petclinic"
                  }
                },
                {
                    "name": "xml",
                    "type": "chePlugin",
                    "id": "redhat.vscode-xml:0.3.0"
                },
                {
                  "name": "fortune",
                  "type": "chePlugin",
                  "id": "org.eclipse.che.samples.container-fortune:0.0.1"
                }
              ],
              "commands": [
                {
                  "name": "build",
                  "actions": [
                    {
                        "type": "exec",
                        "command": "mvn package",
                        "component": "mvn-stack",
                        "workdir": "/projects/spring-petclinic"
                    }
                  ]
                },
                {
                  "name": "run spring",
                  "actions": [
                    {
                      "command": "mvn spring-boot:run",
                      "component": "mvn-stack",
                      "type": "exec",
                      "workdir": "/projects/spring-petclinic"
                    }
                  ]
                },
                {
                  "name": "run mysql",
                  "actions": [
                    {
                      "command": "mvn spring-boot:run",
                      "component": "mysql",
                      "type": "start"
                    }
                  ],
                  "attributes": {
                    "runType": "sequential"
                  }
                }
              ],
              "projects": [
                  {
                      "name": "petclinic",
                      "source": {
                          "location": "https://github.com/spring-projects/spring-petclinic.git",
                          "type": "git"
                      }
                  }
              ]
            }
          }
        }
      ]
    capabilities: Basic Install
  name: che-workspace-crd-operator.v0.0.1
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Workspace
      name: workspaces.workspace.che.eclipse.org
      version: v1alpha1
      description: |
        Eclipse Che 7 workspace based on a Devfile description,
        that provides all required information related to the project
        development environment
      displayName: Che Workspace
      specDescriptors:
        - description: Expected status
          displayName: Started
          path: started
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:booleanSwitch'      
      statusDescriptors:
        - description: Workspace Status
          displayName: Status
          path: phase
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.phase'
        - description: URL to have access to the online IDE
          displayName: IDE URL
          path: ideUrl
          x-descriptors:
            - 'urn:alm:descriptor:org.w3:link'
        - description: Workspace ID
          displayName: Workspace ID
          path: workspaceId
          x-descriptors:
            - 'urn:alm:descriptor:text'
        - description: Conditions
          displayName: Conditions
          path: conditions
          x-descriptors:
            - 'urn:alm:descriptor:io.kubernetes.conditions'
        - description: The status of the Pods started by the workspace
          displayName: Member Pod Status
          path: members
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:podStatuses'
  description: |
    Start an Eclipse Che 7 workspace based on a Devfile description,
    that provides all required information related to the project
    development environment
  displayName: Che Workspace CRD Operator
  install:
    spec:
      deployments:
      - name: che-workspace-crd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: che-workspace-crd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: che-workspace-crd-operator
            spec:
              containers:
              - command:
                - che-workspace-crd-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: che-workspace-crd-operator
                image: quay.io/che-incubator/che-workspace-crd-controller:latest
                imagePullPolicy: Always
                name: che-workspace-crd-operator
                resources: {}
              serviceAccountName: che-workspace-crd-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - extensions
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - che-workspace-crd-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - workspace.che.eclipse.org
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: che-workspace-crd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
