apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workspaceexposures.workspace.che.eclipse.org
spec:
  group: workspace.che.eclipse.org
  names:
    kind: WorkspaceExposure
    listKind: WorkspaceExposureList
    plural: workspaceexposures
    singular: workspaceexposure
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: WorkspaceExposure is the Schema for the workspaceexposures API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceExposureSpec defines the desired state of WorkspaceExposure
          properties:
            exposed:
              description: Should the workspace be exposed ?
              type: boolean
            exposureClass:
              description: 'Class of the exposure: this drives which Workspace exposer
                controller will manage this exposure'
              type: string
            ingressGlobalDomain:
              description: ingress global domain (corresponds to the Openshift route
                suffix)
              type: string
            services:
              additionalProperties:
                properties:
                  endpoints:
                    description: Endpoints that correspond to this machine-related
                      service
                    items:
                      description: Describes dockerimage component endpoint
                      properties:
                        attributes:
                          additionalProperties:
                            type: string
                          type: object
                        name:
                          type: string
                        port:
                          format: int64
                          type: integer
                      required:
                      - name
                      - port
                      type: object
                    type: array
                  serviceName:
                    description: Service name of the machine-related service
                    type: string
                required:
                - endpoints
                - serviceName
                type: object
              description: Services by machine name
              type: object
            workspacePodSelector:
              additionalProperties:
                type: string
              description: Selector that shoud be used by created services to point
                to the workspace Pod
              type: object
          required:
          - exposed
          - exposureClass
          - ingressGlobalDomain
          - services
          - workspacePodSelector
          type: object
        status:
          description: WorkspaceExposureStatus defines the observed state of WorkspaceExposure
          properties:
            exposedEndpoints:
              additionalProperties:
                items:
                  properties:
                    attributes:
                      additionalProperties:
                        type: string
                      description: Attributes of the exposed endpoint
                      type: object
                    name:
                      description: Name of the exposed endpoint
                      type: string
                    url:
                      description: Url of the exposed endpoint
                      type: string
                  required:
                  - name
                  - url
                  type: object
                type: array
              type: object
            phase:
              description: Workspace Exposure status
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
