apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workspaces.workspace.che.eclipse.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.workspaceId
    description: The workspace's unique id
    name: Workspace ID
    type: string
  - JSONPath: .status.phase
    description: The current workspace startup phase
    name: Phase
    type: string
  - JSONPath: .status.ideUrl
    description: Url endpoint for accessing workspace
    name: URL
    type: string
  group: workspace.che.eclipse.org
  names:
    kind: Workspace
    listKind: WorkspaceList
    plural: workspaces
    singular: workspace
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Workspace is the Schema for the workspaces API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: WorkspaceSpec defines the desired state of Workspace
          properties:
            devfile:
              description: 'Workspace Structure defined in the Devfile format syntax.
                For more details see the Che 7 documentation: https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/'
              properties:
                apiVersion:
                  description: Devfile API version
                  type: string
                attributes:
                  description: Devfile attributes, e.g. persistVolumes
                  properties:
                    editorFree:
                      type: boolean
                    persistVolumes:
                      type: boolean
                  type: object
                commands:
                  description: List of workspace-wide commands that can be associated
                    to a given component, in order to run in the related container
                  items:
                    properties:
                      actions:
                        items:
                          properties:
                            command:
                              type: string
                            component:
                              type: string
                            reference:
                              type: string
                            referenceContent:
                              type: string
                            type:
                              type: string
                            workdir:
                              type: string
                          required:
                          - type
                          type: object
                        type: array
                      attributes:
                        additionalProperties:
                          type: string
                        type: object
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
                components:
                  description: List of components (editor, plugins, containers, ...)
                    that will provide the workspace features
                  items:
                    properties:
                      alias:
                        type: string
                      args:
                        items:
                          type: string
                        type: array
                      command:
                        items:
                          type: string
                        type: array
                      endpoints:
                        items:
                          description: Describes dockerimage component endpoint
                          properties:
                            attributes:
                              additionalProperties:
                                type: string
                              type: object
                            name:
                              type: string
                            port:
                              format: int64
                              type: integer
                          required:
                          - name
                          - port
                          type: object
                        type: array
                      env:
                        items:
                          description: Describes environment variable
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                          - name
                          - value
                          type: object
                        type: array
                      id:
                        type: string
                      image:
                        type: string
                      memoryLimit:
                        type: string
                      mountSources:
                        type: boolean
                      reference:
                        type: string
                      referenceContent:
                        type: string
                      selector:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                      volumes:
                        items:
                          description: Describe volume that should be mount to component
                          properties:
                            containerPath:
                              type: string
                            name:
                              type: string
                          required:
                          - containerPath
                          - name
                          type: object
                        type: array
                    required:
                    - type
                    type: object
                  type: array
                metadata:
                  description: Devfile metadata
                  properties:
                    generateName:
                      type: string
                    name:
                      type: string
                  type: object
                projects:
                  description: List of projects that should be imported into the workspace
                  items:
                    properties:
                      name:
                        type: string
                      source:
                        description: Describes the project's source - type and location
                        properties:
                          location:
                            type: string
                          type:
                            type: string
                        required:
                        - location
                        - type
                        type: object
                    required:
                    - name
                    - source
                    type: object
                  type: array
              required:
              - components
              type: object
            routingClass:
              description: Routing class the defines how the workspace will be exposed
                to the external network
              type: string
            started:
              description: Whether the workspace should be started or stopped
              type: boolean
          required:
          - devfile
          - started
          type: object
        status:
          description: WorkspaceStatus defines the observed state of Workspace
          properties:
            additionalFields:
              description: 'TODO: This could potentially be handled via configmap
                more cleanly'
              properties:
                org.eclipse.che.workspace/runtime:
                  type: string
              required:
              - org.eclipse.che.workspace/runtime
              type: object
            condition:
              description: Conditions represent the latest available observations
                of an object's state
              items:
                description: WorkspaceCondition contains details for the current condition
                  of this workspace.
                properties:
                  lastTransitionTime:
                    description: Last time the condition transitioned from one status
                      to another.
                    format: date-time
                    type: string
                  message:
                    description: Human-readable message indicating details about last
                      transition.
                    type: string
                  reason:
                    description: Unique, one-word, CamelCase reason for the condition's
                      last transition.
                    type: string
                  status:
                    description: Phase is the status of the condition. Can be True,
                      False, Unknown.
                    type: string
                  type:
                    description: Type is the type of the condition.
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            ideUrl:
              type: string
            phase:
              type: string
            workspaceId:
              type: string
          required:
          - ideUrl
          - workspaceId
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
