---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-controller
  namespace: che-workspace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-workspace-controller
  template:
    metadata:
      labels:
        app: che-workspace-controller
    spec:
      serviceAccountName: che-workspace-controller
      containers:
        - name: che-workspace-controller
          image: sleshchenko/che-workspace-controller:webhook
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "che-workspace-operator"
          ports:
            - name: webhook-server
              containerPort: 8443
---
#TODO move creating of it on fly if needed
apiVersion: v1
kind: Service
metadata:
  labels:
    app: che-workspace-controller
  name: workspace-controller
  namespace: che-workspace-controller
spec:
  ports:
    - targetPort: webhook-server
      protocol: TCP
      port: 443
  selector:
    app: che-workspace-controller
