apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-workspace-controller-cert-gen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-workspace-controller-cert-gen
  template:
    metadata:
      labels:
        app: che-workspace-controller-cert-gen
        app.kubernetes.io/name: devworkspace-controller
        app.kubernetes.io/part-of: devworkspace-controller
      annotations:
        kubectl.kubernetes.io/restartedAt: ""
    spec:
      serviceAccountName: che-workspace-controller
      containers:
        - name: che-workspace-controller-cert-gen
          image: quay.io/che-incubator/che-workspace-controller-cert-gen:nightly
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
