apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: workspace-controller
  labels:
    app: che-workspace-controller
  name: workspace-controller
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook-server
  selector:
    app: che-workspace-controller
  sessionAffinity: None
  type: ClusterIP
