# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by deploy/templates/default
resources:
- bases/controller.devfile.io_components.yaml
- bases/controller.devfile.io_devworkspaceroutings.yaml
- bases/workspace.devfile.io_devworkspaces.yaml
- bases/workspace.devfile.io_devworkspacetemplates.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
